In [3]:
import yaml
import io
import numpy as np
import pandas as pd
from sys import argv

n_PWs = 51

table = pd.DataFrame([0 for i in range(n_PWs)])

In [4]:
for i in range(n_PWs):
    data_loaded = None
    with open("4-PWs/CEN-NDC-regions_{}_mnpw.yaml".format(i), 'r') as stream:
        data_loaded = yaml.load(stream)
    for key, subdict in data_loaded.items():
        if 'group' in subdict:
            group = subdict['group']
            if group in table:
                table.set_value(i, group, table.iloc[i][group]+1)
            else:
                table[group] = 0
                table.set_value(i, group, 1)
        if 'label' in subdict:
            label = subdict['label']
            if label in table:
                table.set_value(i, label, table.iloc[i][label]+1)
            else:
                table[label] = 0
                table.set_value(i, label, 1)
table = table.drop(0, axis = 1)
table

,CEN,NDC,congruent,is_a (inferred),is_a (input),overlaps (inferred),overlaps (input)
0,4,5,1,2,7,2,1
1,4,5,1,2,7,1,1
2,4,5,1,2,7,2,1
3,4,5,1,1,8,3,1
4,4,5,1,1,8,4,1
5,4,5,1,2,7,1,1
6,4,5,1,2,7,2,1
7,4,5,1,2,7,1,1
8,4,5,1,2,7,2,1
9,4,5,1,1,8,3,1
10,4,5,1,1,8,4,1
11,4,5,1,1,8,3,1
12,4,5,1,1,8,4,1
13,4,5,1,1,8,2,1
14,4,5,1,1,8,3,1
15,4,5,1,1,8,3,1
16,4,5,1,1,8,4,1
17,4,5,1,0,9,4,1
18,4,5,1,0,9,5,1
19,4,5,1,0,9,5,1
20,4,5,1,0,9,6,1
21,3,4,2,0,8,2,1
22,4,5,1,1,8,3,1
23,4,5,1,1,8,3,1
24,4,5,1,1,8,4,1
25,4,5,1,1,8,3,1
26,4,5,1,0,9,5,1
27,4,5,1,0,9,4,1
28,4,5,1,0,9,5,1
29,4,5,1,0,9,5,1
30,4,5,1,0,9,6,1
31,4,5,1,1,8,2,1
32,4,5,1,1,8,3,1
33,4,5,1,0,9,4,1
34,4,5,1,0,9,5,1
35,4,5,1,0,9,4,1
36,4,5,1,0,9,5,1
37,4,5,1,0,9,5,1
38,4,5,1,0,9,6,1
39,4,5,1,1,8,3,1
40,4,5,1,1,8,4,1
41,4,5,1,0,9,5,1
42,4,5,1,0,9,6,1
43,4,5,1,0,9,4,1
44,4,5,1,0,9,5,1
45,4,5,1,0,9,5,1
46,4,5,1,0,9,6,1
47,4,5,1,0,9,5,1
48,4,5,1,0,9,6,1
49,4,5,1,0,9,6,1
50,4,5,1,0,9,7,1

In [5]:
table.to_csv('extracted_stats.csv')